# delelopment
system:
  # 设定模式(debug/release/test,正式版改为release)
  mode: debug
  # url前缀
  url-path-prefix: api/auth
  # 程序监听端口
  port: 8088
  # rsa公钥文件路径(config.yml相对路径, 也可以填绝对路径)
  rsa-public-key: fastgin-pub.pem
  # rsa私钥文件路径(config.yml相对路径, 也可以填绝对路径)
  rsa-private-key: fastgin-priv.pem

logs:
  # 日志等级(-1:Debug, 0:Info, 1:Warn, 2:Error, 3:DPanic, 4:Panic, 5:Fatal, -1<=level<=5, 参照zap.level源码)
  level: -1
  # 日志路径
  path: logs
  # 文件最大大小, M
  max-size: 50
  # 备份数
  max-backups: 100
  # 存放时间, 天
  max-age: 30
  # 是否压缩
  compress: false
database:
  # 数据库类型(mysql,sqlite3)
  type: mysql
  create-tables: false
  # 是否初始化数据(没有初始数据时使用, 已发布正式版改为false)
  init-data: false
  sqlite:
    # 数据库文件路径(config.yml相对路径, 也可以填绝对路径)
    file-path: go_web_mini.db
  mysql:
    # 用户名
    username: root
    # 密码
    password: root
    # 数据库名
    database: fastgin
    # 主机地址
    host: localhost
    # 端口
    port: 3306
    # 连接字符串参数
    query: parseTime=True&loc=Local&timeout=10000ms
    # 是否打印日志
    log-mode: true
    # 数据库表前缀(无需再末尾添加下划线, 程序内部自动处理)
    table-prefix: tb
    # 编码方式
    charset: utf8mb4
    # 字符集(utf8mb4_general_ci速度比utf8mb4_unicode_ci快些)
    collation: utf8mb4_general_ci

# casbin配置
casbin:
  # 模型配置文件, config.yml相对路径
  model-path: 'conf/rbac_model.conf'

# jwt配置
jwt:
  # jwt标识
  realm: test jwt
  # 服务端密钥
  key: secret key
  # token过期时间, 小时
  timeout: 12
  # 刷新token最大过期时间, 小时
  max-refresh: 12

# 令牌桶限流配置
rate-limit:
  # 填充一个令牌需要的时间间隔,毫秒
  fill-interval: 50
  # 桶容量
  capacity: 200

storage: "conf/storage.yml"

captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  open-captcha: 0
  open-captcha-timeout: 3600

email:
  host: smtp.qq.com
  port: 587
  account: 1234567848@qq.com
  password: oztajemlxoagebhc
  is-ssl: true
  from: fastgin
  blackmail: [anonymousemail.me,sharklasers.com,guerrillamail.info,grr.la,guerrillamail.biz,guerrillamail.com,guerrillamail.de,guerrillamail.net,guerrillamail.org,guerrillamailblock.com,pokemail.net,spam4.me,chacuo.net,027168.com,stypedia.com,maildrop.cc,1xp.fr,cpc.cx,0cd.cn,prc.cx,ab34.fr,e3b.org,new.ovh,o--b.tk,ves.ink,ip11.tk,tokai.tk,q0.us.to,zx81.ovh,wishy.fr,otiss.gq,bmn.ch.ma,iya.fr.nf,sdj.fr.nf,afw.fr.nf,mail34.fr,mynes.com,dao.pp.ua,jjnan.com,nori24.tv,lerch.ovh,breizh.im,six25.biz,art.fr.cr,red.fr.cr,ywzmb.top,isep.fr.nf,noreply.fr,pliz.fr.nf,noyp.fr.nf,zouz.fr.nf,hunnur.com,wxcv.fr.nf,zorg.fr.nf,imap.fr.nf,redi.fr.nf,dlvr.us.to,y.iotf.net,zinc.fr.nf,ym.cypi.fr,yop.too.li,dmts.fr.nf,binich.com,wzofit.com,battery.pw,jmail.fr.nf,zimel.fr.cr,yaloo.fr.nf,jinva.fr.nf,darty.fr.cr,ag.prout.be,ba.prout.be,es.prout.be,us.prout.be,ealea.fr.nf,nomes.fr.nf,yop.kd2.org,alves.fr.nf,bibi.biz.st,ymail.rr.nu,bboys.fr.nf,ma.ezua.com,ma.zyns.com,mai.25u.com,nomes.fr.cr,autre.fr.nf,mail.n3t.be,lsyx0.rr.nu,tweet.fr.nf,pamil.1s.fr,pamil.fr.nf,ymail.1s.fr,15963.fr.nf,popol.fr.nf,pmail.1s.fr,flobo.fr.nf,toolbox.ovh,bin-ich.com,sindwir.com,mabal.fr.nf,degap.fr.nf,yop.uuii.in,jetable.org,ypm.liame.tk,pasdus.fr.cr,gland.xxl.st,nospam.fr.nf,azeqsd.fr.nf,le.monchu.fr,nikora.fr.nf,sendos.fr.nf,mai.dhcp.biz,cubox.biz.st,fhpfhp.fr.nf,c-eric.fr.nf,c-eric.fr.cr,bahoo.biz.st,upc.infos.st,gggggg.fr.cr,spam.aleh.de,alphax.fr.nf,habenwir.com,ist-hier.com,sind-wir.com,sindhier.com,wir-sind.com,myself.fr.nf,yop.mabox.eu,vip.ep77.com,email.jjj.ee,atriox.rf.gd,paulprems.cf,yahooz.xxl.st,tiscali.fr.cr,altrans.fr.nf,yoptruc.fr.nf,kyuusei.fr.nf,ac-cool.c4.fr,certexx.fr.nf,dede.infos.st,sake.prout.be,eureka.0rg.fr,yotmail.fr.nf,miloras.fr.nf,nikora.biz.st,cabiste.fr.nf,galaxim.fr.nf,fuppurge.info,doviaso.fr.cr,pitiful.pp.ua,ggmail.biz.st,dis.hopto.org,yop.kyriog.fr,1.8259law.com,icidroit.info,alkonealko.cz,yop.mc-fly.be,spam.9001.ovh,tmp.x-lab.net,mail.hsmw.net,y.dldweb.info,haben-wir.com,sind-hier.com,adresse.fr.cr,assurmail.net,yop.smeux.com,korekgas.info,altmailact.tk,alyxgod.rf.gd,mailbox.biz.st,elmail.4pu.com,carioca.biz.st,mickaben.fr.nf,mickaben.fr.cr,ac-malin.fr.nf,gimuemoa.fr.nf,woofidog.fr.nf,rygel.infos.st,cheznico.fr.cr,contact.biz.st,rapidefr.fr.nf,calendro.fr.nf,calima.asso.st,cobal.infos.st,terre.infos.st,imails.asso.st,warlus.asso.st,carnesa.biz.st,jackymel.xl.cx,mail.tbr.fr.nf,webstore.fr.nf,freemail.fr.cr,mr-email.fr.nf,abo-free.fr.nf,courrier.fr.cr,ymail.ploki.fr,mailsafe.fr.nf,mail.jab.fr.cr,testkkk.zik.dj,sirttest.us.to,yop.moolee.net,antispam.fr.nf,machen-wir.com,adresse.biz.st,poubelle.fr.nf,lacraffe.fr.nf,gladogmi.fr.nf,yopmail.ozm.fr,mail.yabes.ovh,totococo.fr.nf,miistermail.fr,freemail.biz.st,skynet.infos.st,readmail.biz.st,frostmail.fr.nf,frostmail.fr.cr,pitimail.xxl.st,mickaben.biz.st,mickaben.xxl.st,internaut.us.to,askold.prout.be,poubelle-du.net,mondial.asso.st,randol.infos.st,himail.infos.st,sendos.infos.st,nidokela.biz.st,likeageek.fr.nf,spam.popcorp.eu,mcdomaine.fr.nf,emaildark.fr.nf,y.jerrycraft.tk,spam.quillet.eu,desfrenes.fr.nf,mymail.infos.st,mail.i-dork.com,mesemails.fr.nf,dripzgaming.com,mymaildo.kro.kr,saruawaeah.co.uk,m.tartinemoi.com,cool.fr.nf,courriel.fr.nf,jetable.fr.nf,mega.zik.dj,moncourrier.fr.nf,monemail.fr.nf,monmail.fr.nf,nomail.xl.cx,nospam.ze.tc,speed.1s.fr,yopmail.com,yopmail.fr,yopmail.net,nezid.com]