// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameApi = "sys_api"

// Api mapped from table <sys_api>
type Api struct {
	ID        uint64         `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	Method    string         `gorm:"column:method;type:varchar(20);comment:'请求方式'" json:"method"`     // '请求方式'
	Path      string         `gorm:"column:path;type:varchar(100);comment:'访问路径'" json:"path"`        // '访问路径'
	Category  string         `gorm:"column:category;type:varchar(50);comment:'所属类别'" json:"category"` // '所属类别'
	Des       string         `gorm:"column:des;type:varchar(100);comment:'说明'" json:"des"`            // '说明'
	Creator   string         `gorm:"column:creator;type:varchar(20);comment:'创建人'" json:"creator"`    // '创建人'
}

// TableName Api's table name
func (*Api) TableName() string {
	return TableNameApi
}
