// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOperationLog = "sys_operation_log"

// OperationLog mapped from table <sys_operation_log>
type OperationLog struct {
	ID         uint64         `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt  time.Time      `gorm:"column:created_at;type:datetime(3);default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;type:datetime(3);default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	UserName   string         `gorm:"column:user_name;type:varchar(20);comment:'用户登录名'" json:"user_name"`                               // '用户登录名'
	IP         string         `gorm:"column:ip;type:varchar(20);comment:'Ip地址'" json:"ip"`                                              // 'Ip地址'
	IPLocation string         `gorm:"column:ip_location;type:varchar(20);comment:'Ip所在地'" json:"ip_location"`                           // 'Ip所在地'
	Method     string         `gorm:"column:method;type:varchar(20);comment:'请求方式'" json:"method"`                                      // '请求方式'
	Path       string         `gorm:"column:path;type:varchar(100);comment:'访问路径'" json:"path"`                                         // '访问路径'
	Des        string         `gorm:"column:des;type:varchar(100);comment:'说明'" json:"des"`                                             // '说明'
	Status     int32          `gorm:"column:status;type:int(4);comment:'响应状态码'" json:"status"`                                          // '响应状态码'
	StartTime  time.Time      `gorm:"column:start_time;type:datetime(3);default:CURRENT_TIMESTAMP(3);comment:'发起时间'" json:"start_time"` // '发起时间'
	TimeCost   int32          `gorm:"column:time_cost;type:int(6);comment:'请求耗时(ms)'" json:"time_cost"`                                 // '请求耗时(ms)'
	UserAgent  string         `gorm:"column:user_agent;type:varchar(20);comment:'浏览器标识'" json:"user_agent"`                             // '浏览器标识'
}

// TableName OperationLog's table name
func (*OperationLog) TableName() string {
	return TableNameOperationLog
}
