// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDictionary = "web_dictionary"

// Dictionary 字典表
type Dictionary struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                  // ID
	CreatedAt time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                              // 删除时间
	Key       string         `gorm:"column:key;comment:配置的Key" json:"key"`                                          // 配置的Key
	Value     string         `gorm:"column:value;comment:配置的值" json:"value"`                                        // 配置的值
	Des       string         `gorm:"column:des;comment:说明" json:"des"`                                              // 说明
}

// TableName Dictionary's table name
func (*Dictionary) TableName() string {
	return TableNameDictionary
}
